int atmega64_int[]={
  RESET,INT0,INT1,INT2,INT3,INT4,INT5,INT6,INT7,TIMER2_COMP,TIMER2_OVF,
  TIMER1_CAPT,TIMER1_COMPA,TIMER1_COMPB,TIMER1_OVF,TIMER0_COMP,TIMER0_OVF,
  SPI_STC,UART0_RX,UART0_UDRE,UART0_TX,ADC,EE_READY,ANALOG_COMP,TIMER1_COMPC,
  TIMER3_CAPT,TIMER3_COMPA,TIMER3_COMPB,TIMER3_COMPC,TIMER3_OVF,UART1_RX,
  UART1_UDRE,UART1_TX,TWSI,SPM_RDY,-1};

